routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/migrasi/migrasi1', 'Migration\Migrasi1Controller@index')->name('migration.migrasi1');


// Route::get('/migrasi/testingmigrasi', 'Migration\Migrasi1Controller@testing')->name('migration.testing');
Route::group(['middleware' => 'auth'], function() {
	Route::get('/', 'SatuanController@redirectToIndex')->name('redirectTo.index');
	Route::get('/dashboard','DashboardController@index')->name('dashboard.index');
	Route::get('/duplikasi-satuan', 'SatuanController@getDuplikasi')->name('satuan.duplication.get');
	Route::post('/duplikasi-satuan', 'SatuanController@postDuplikasi')->name('satuan.duplication.post');
	Route::get('/personel', 'PersonelController@index')->name('personel.index');
	Route::get('/migration', 'Migration\MigrationController@index')->name('migration.index');
	Route::post('/migration/reset-satuan-jabatan', 'MigrationController@resetSatuanJabatan')->name('migration.reset.satuan-jabatan');
	Route::post('/migration/reset-personel', 'MigrationController@resetPersonel')->name('migration.reset.personel');
	Route::get('/migration/insert-jabatan', 'MigrationController@insertJabatan')->name('migration.insert.jabatan');
	Route::post('/migration/seed', 'MigrationController@seed')->name('migration.seed');
	Route::get('/personel/{personel}/edit', 'PersonelController@edit')->name('personel.edit');
	Route::post('/personel/{personel}/update', 'PersonelController@update')->name('personel.update');
	Route::get('/personel/filter', 'PersonelController@filter')->name('personel.filter');
	Route::get('/personel/duplicate', 'PersonelController@duplicate')->name('personel.duplicate');
	Route::patch('/personel/verification/{id}', 'PersonelController@verification')->name('personel.verification');
	Route::get('/personel/create', 'PersonelController@create')->name('personel.create');


	Route::post('/satuan/filter', 'SatuanController@filter')->name('satuan.filter');
	Route::resource('/satuan','SatuanController');
	Route::get('/satuan/{satuan}/create-satuan', 'SatuanController@createSatuan')->name('satuan.create-satuan');
	// Route::get('/get-data-wiget/{satuan}', 'SatuanController@APIdataWidget')->name('satuan.api-data-widget');
	Route::post('/satuan/{satuan}/store-satuan', 'SatuanController@storeSatuan')->name('satuan.store-satuan');
	Route::get('/satuan/{satuan}/create-jabatan', 'SatuanController@createJabatan')->name('satuan.create-jabatan');
	Route::post('/satuan/{satuan}/store-jabatan', 'SatuanController@storeJabatan')->name('satuan.store-jabatan');
	Route::get('/satuan/verification/{satuan}', 'SatuanController@verification')->name('satuan.verification');
	Route::get('/satuan/{satuan}/edit-jabatan/{satuanJabatan}', 'SatuanJabatanController@edit')->name('satuan-jabatan.edit');
	Route::patch('/satuan/{satuan}/update-jabatan/{satuanJabatan}', 'SatuanJabatanController@update')->name('satuan-jabatan.update');
	Route::delete('/satuan/{satuan}/delete-jabatan/{satuanJabatan}', 'SatuanJabatanController@destroy')->name('satuan-jabatan.destroy');
	Route::post('/satuan/{satuan}/verification/{satuanJabatan}', 'SatuanJabatanController@verification')->name('satuan-jabatan.verification');
	Route::post('/satuan/{satuan}/data-error/{satuanJabatan}', 'SatuanJabatanController@dataError')->name('satuan-jabatan.data-error');


	Route::get('/jabatan-filter', 'JabatanController@filter')->name('jabatan.filter');


	Route::resource('/jenis-satuan','JenisSatuanController');
	Route::resource('/jabatan','JabatanController');
	Route::resource('/pangkat','PangkatController');
	Route::resource('/nivelering','NiveleringController');


});

Route::get('/testing-request','API\FileController@getFileTesting');
Route::get('/report-harian','ReportController@reportHarian')->name('report.harian');
Route::get('/', 'UserController@getLogin');
// Duplication
	Route::get('/duplication/duplikasi','Duplication\DuplicationController@halamanDuplikasi')->name('duplication.halamanDuplikasi');
	Route::get('/duplication/sort','Duplication\DuplicationController@sort')->name('duplication.sort');
	Route::get('/duplication/satuan-masalah','Duplication\DuplicationController@cariSatuanBermasalah')->name('duplication.cariSatuanBermasalah');
	// set Kepala Atasan
	// set Nivelering
	Route::get('/duplication/nivelering-norm','Duplication\NiveleringController@niveleringNormalisasi')->name('duplication.niveleringNormalisasi');
	Route::get('/duplication/hapusSatuanKerja','Duplication\DuplicationController@hapusSatuanKerja')->name('duplication.hapusSatuanKerja');
	Route::get('/duplication/hapusSeluruhJabatan','Duplication\DuplicationController@hapusSeluruhJabatan')->name('duplication.hapusSeluruhJabatan');
	Route::get('/masalah/polsubsektor','SatuanController@masalahPolsubsektor')->name('duplication.masalahPolsubsektor');
	Route::get('/masalah/tambah-keterangan-satuan','SatuanController@tambahKeteranganSatuan')->name('duplication.tambahKeteranganSatuan');
	Route::get('/masalah/satuan-double','SatuanController@masalahSatuanDouble')->name('duplication.masalahSatuanDouble');
Route::get('/nivelering-norm','Duplication\DuplicationController@niveleringNormalisasi')->name('duplication.niveleringNormalisasi');
Route::get('/create-eselon','Duplication\DuplicationController@createEselon')->name('duplication.createEselon');
Route::get('/login', 'UserController@getLogin')->name('login');
Route::post('/login', 'UserController@postLogin')->name('user.login.post');
Route::get('/logout', 'UserController@logout')->name('user.logout');



Route::group(['prefix'=>'laporan','namespace'=> 'Laporan','as'=>'laporan.'],function(){
	Route::get('/', 'DashboardController@redirectToLogin');
	Route::get('/login', 'LoginController@getLogin')->name('login.get');
	Route::post('/login', 'LoginController@postLogin')->name('login.post');
	Route::group(['middleware' => 'auth:verifikator'],function(){
		Route::get('/', 'DashboardController@dashboard')->name('dashboard');
	});
});

app/JenisSatuan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class JenisSatuan extends Model
{
	protected $primaryKey = 'jenis_satuan_id';
	protected $table = 'jenis_satuan';
	protected $guarded = [];
	public $timestamps = false;

	public function satuan()
	{
		return $this->hasMany(Satuan::class,'jenis_satuan_id');
	}
}

app/Http/Controllers/JenisSatuanController.php
<?php

namespace App\Http\Controllers;

use App\JenisSatuan;
use Illuminate\Http\Request;

class JenisSatuanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('jenis-satuan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $jenisSatuan = JenisSatuan::create($request->except('_token'));

        if($jenisSatuan){
            return redirect()->route('satuan.index')->with('success','Buat jenis satuan berhasil dilakukan.');
        }
        else {
            return redirect()->route('satuan.index')->with('error','Buat jenis satuan gagal dilakukan.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(JenisSatuan $jenisSatuan)
    {
        $dataSatuan = $jenisSatuan->satuan()->paginate(10);
        return view('jenis-satuan.edit',compact('jenisSatuan','dataSatuan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, JenisSatuan $jenisSatuan)
    {
        if($jenisSatuan->update($request->except('_token'))){
            return redirect()->route('satuan.index')->with('success','Buat jenis satuan berhasil dilakukan.');
        }
        else {
            return redirect()->route('satuan.index')->with('error','Buat jenis satuan gagal dilakukan.');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(JenisSatuan $jenisSatuan)
    {
        if($jenisSatuan->delete()){
            return redirect()->route('satuan.index')->with('success','Hapus jenis satuan berhasil dilakukan.');
        }
        else {
            return redirect()->route('satuan.index')->with('error','Hapus jenis satuan gagal dilakukan.');
        }
        
    }
}

resources/views/jenis-satuan/create.blade.php
@extends('layouts.default')

@section('content')
	<div class="container-fluid">
	    <div class="block-header">
	        <h2>DASHBOARD</h2>
	    </div>

	    @if(Session::has('success'))
		    <div class="alert alert-success">{{Session::get('success')}}</div>
	    @endif

	    @if(Session::has('error'))
		    <div class="alert alert-error">{{Session::get('error')}}</div>
	    @endif

	    <!-- Filter -->
	    <div class="row clearfix" id="filter">
	        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
	            <div class="card">
	                <div class="header">
	                    <h2>BUAT JENIS SATUAN BARU</h2>
	                </div>
	                <div class="body">
	                    <form id="form_validation" class="form-horizontal" method="POST" action="{{ route('jenis-satuan.store')}}">
	                        {{ csrf_field() }}
	                        <div class="row clearfix">
	                            <div class="col-md-12">
	                                <div class="row clearfix">
	                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-5 form-control-label">
	                                        <label for="nama_jenis_satuan">NAMA JENIS SATUAN</label>
	                                    </div>
	                                    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-7">
	                                        <div class="form-group" style="margin:0px;">
	                                            <div class="form-line" style="padding-left:12px;">
	                                                <input id="nama_jenis_satuan" name="nama_jenis_satuan" class="form-control" placeholder="Nama Satuan" type="text">
	                                            </div>
	                                        </div>
	                                    </div>
	                                </div>
	                                <div class="row clearfix">
	                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-5 form-control-label">
	                                        <label for="kategori">KATEGORI SATUAN</label>
	                                    </div>
	                                    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-7">
		                                    <select class="form-control show-tick" name="kategori" id="kategori">
		                                        <option value="SATUAN KERJA">SATUAN KERJA</option>
		                                        <option value="SATUAN WILAYAH">SATUAN WILAYAH</option>
		                                    </select>
	                                    </div>
	                                </div>
	                                <div class="row clearfix">
	                                    <div class="col-md-8 col-md-offset-4">
	                                        <button type="submit" class="btn bg-green btn-lg btn-block waves-effect"><label>BUAT</label></button>
	                                    </div>
	                                </div>
	                            </div>
	                        </div>
	                    </form>
	                </div>
	            </div>
	        </div>
	    </div>
	    <!-- End Filter -->
@endsection

@section('script')
@endsection

resources/views/jenis-satuan/edit.blade.php
@extends('layouts.default')

@section('content')
	<div class="container-fluid">
	    <div class="block-header">
	        <h2>DASHBOARD</h2>
	    </div>

	    @if(Session::has('success'))
		    <div class="alert alert-success">{{Session::get('success')}}</div>
	    @endif

	    @if(Session::has('error'))
		    <div class="alert alert-error">{{Session::get('error')}}</div>
	    @endif

	    <!-- Filter -->
	    <div class="row clearfix" id="filter">
	        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
	            <div class="card">
	                <div class="header">
	                    <h2>EDIT JENIS SATUAN BARU</h2>
	                </div>
	                <div class="body">
	                    <form id="form_validation" class="form-horizontal" method="POST" action="{{ route('jenis-satuan.update',$jenisSatuan->jenis_satuan_id)}}">
	                    	<input type="hidden" name="_method" value="PATCH">
	                        {{ csrf_field() }}
	                        <div class="row clearfix">
	                            <div class="col-md-12">
	                                <div class="row clearfix">
	                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-5 form-control-label">
	                                        <label for="nama_jenis_satuan">NAMA JENIS SATUAN</label>
	                                    </div>
	                                    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-7">
	                                        <div class="form-group" style="margin:0px;">
	                                            <div class="form-line" style="padding-left:12px;">
	                                                <input id="nama_jenis_satuan" name="nama_jenis_satuan" class="form-control" placeholder="Nama Satuan" type="text" value="{{$jenisSatuan->nama_jenis_satuan}}">
	                                            </div>
	                                        </div>
	                                    </div>
	                                </div>
	                                <div class="row clearfix">
	                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-5 form-control-label">
	                                        <label for="kategori">KATEGORI SATUAN</label>
	                                    </div>
	                                    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-7">
		                                    <select class="form-control show-tick" name="kategori" id="kategori">
		                                        <option value="SATUAN KERJA">SATUAN KERJA</option>
		                                        <option value="SATUAN WILAYAH">SATUAN WILAYAH</option>
		                                    </select>
	                                    </div>
	                                </div>
	                                <div class="row clearfix">
	                                    <div class="col-md-8 col-md-offset-4">
	                                        <button type="submit" class="btn bg-green btn-lg btn-block waves-effect"><label>SAVE</label></button>
	                                    </div>
	                                </div>
	                            </div>
	                        </div>
	                    </form>
	                </div>
	            </div>
	        </div>
	    </div>
	    <!-- End Filter -->


	    <!-- Hover Rows -->
	    <div class="row clearfix">
	        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
	            <div class="card">
	            	<div class="header">
	            	<h2>Daftar Satuan</h2>
	            	</div>
	                <div class="body table-responsive">
	                    <table class="table table-hover" id="table-personel">
	                        <thead>
	                            <tr>
	                                <th>ID</th>
	                                <th width="350px">Nama Satuan</th>
	                                <th width="150px">Jumlah Satuan</th>
	                                <th width="150px">FullPrint</th>
	                                <th width="200px">Tipe Satuan</th>
	                                <th width="100px">Status</th>
	                                <th width="100px">PILIHAN</th>
	                            </tr>
	                        </thead>
	                        <tbody>
	                            @foreach($dataSatuan as $satuan)
	                            <tr style="font-size:12px;">
	                            	<td>{{ $satuan->satuan_id }}</td>
	                            	<td>{{ $satuan->nama_satuan }}</td>
	                            	<td>{{ $satuan->fullPrint() }}</td>
	                            	<td>{{ $satuan->childs()->count() }}</td>
	                            	<td>{{ $satuan->tipe }}</td>
	                            	<td>{!! $satuan->printStatus() !!}
		                            </td>
	                            	<td>
		                            	<a href="{{route('satuan.show',$satuan->satuan_id)}}" class="btn btn-xs bg-blue"><i class="material-icons">pageview</i></a>
	                            	</td>
	                            </tr>
	                            @endforeach
	                        </tbody>
	                    </table>
	                    {{ $dataSatuan->render() }}
	                </div>
	            </div>
	        </div>
	    </div>
	    <!-- #END# Hover Rows -->
@endsection

@section('script')
	<script>
	$("#kategori").val("{{$jenisSatuan->kategori}}");
	</script>
@endsection