routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/migrasi/migrasi1', 'Migration\Migrasi1Controller@index')->name('migration.migrasi1');


// Route::get('/migrasi/testingmigrasi', 'Migration\Migrasi1Controller@testing')->name('migration.testing');
Route::group(['middleware' => 'auth'], function() {
	Route::get('/', 'SatuanController@redirectToIndex')->name('redirectTo.index');
	Route::get('/dashboard','DashboardController@index')->name('dashboard.index');
	Route::get('/duplikasi-satuan', 'SatuanController@getDuplikasi')->name('satuan.duplication.get');
	Route::post('/duplikasi-satuan', 'SatuanController@postDuplikasi')->name('satuan.duplication.post');
	Route::get('/personel', 'PersonelController@index')->name('personel.index');
	Route::get('/migration', 'Migration\MigrationController@index')->name('migration.index');
	Route::post('/migration/reset-satuan-jabatan', 'MigrationController@resetSatuanJabatan')->name('migration.reset.satuan-jabatan');
	Route::post('/migration/reset-personel', 'MigrationController@resetPersonel')->name('migration.reset.personel');
	Route::get('/migration/insert-jabatan', 'MigrationController@insertJabatan')->name('migration.insert.jabatan');
	Route::post('/migration/seed', 'MigrationController@seed')->name('migration.seed');
	Route::get('/personel/{personel}/edit', 'PersonelController@edit')->name('personel.edit');
	Route::post('/personel/{personel}/update', 'PersonelController@update')->name('personel.update');
	Route::get('/personel/filter', 'PersonelController@filter')->name('personel.filter');
	Route::get('/personel/duplicate', 'PersonelController@duplicate')->name('personel.duplicate');
	Route::patch('/personel/verification/{id}', 'PersonelController@verification')->name('personel.verification');
	Route::get('/personel/create', 'PersonelController@create')->name('personel.create');


	Route::post('/satuan/filter', 'SatuanController@filter')->name('satuan.filter');
	Route::resource('/satuan','SatuanController');
	Route::get('/satuan/{satuan}/create-satuan', 'SatuanController@createSatuan')->name('satuan.create-satuan');
	// Route::get('/get-data-wiget/{satuan}', 'SatuanController@APIdataWidget')->name('satuan.api-data-widget');
	Route::post('/satuan/{satuan}/store-satuan', 'SatuanController@storeSatuan')->name('satuan.store-satuan');
	Route::get('/satuan/{satuan}/create-jabatan', 'SatuanController@createJabatan')->name('satuan.create-jabatan');
	Route::post('/satuan/{satuan}/store-jabatan', 'SatuanController@storeJabatan')->name('satuan.store-jabatan');
	Route::get('/satuan/verification/{satuan}', 'SatuanController@verification')->name('satuan.verification');
	Route::get('/satuan/{satuan}/edit-jabatan/{satuanJabatan}', 'SatuanJabatanController@edit')->name('satuan-jabatan.edit');
	Route::patch('/satuan/{satuan}/update-jabatan/{satuanJabatan}', 'SatuanJabatanController@update')->name('satuan-jabatan.update');
	Route::delete('/satuan/{satuan}/delete-jabatan/{satuanJabatan}', 'SatuanJabatanController@destroy')->name('satuan-jabatan.destroy');
	Route::post('/satuan/{satuan}/verification/{satuanJabatan}', 'SatuanJabatanController@verification')->name('satuan-jabatan.verification');
	Route::post('/satuan/{satuan}/data-error/{satuanJabatan}', 'SatuanJabatanController@dataError')->name('satuan-jabatan.data-error');


	Route::get('/jabatan-filter', 'JabatanController@filter')->name('jabatan.filter');


	Route::resource('/jenis-satuan','JenisSatuanController');
	Route::resource('/jabatan','JabatanController');
	Route::resource('/pangkat','PangkatController');
	Route::resource('/nivelering','NiveleringController');


});

Route::get('/testing-request','API\FileController@getFileTesting');
Route::get('/report-harian','ReportController@reportHarian')->name('report.harian');
Route::get('/', 'UserController@getLogin');
// Duplication
	Route::get('/duplication/duplikasi','Duplication\DuplicationController@halamanDuplikasi')->name('duplication.halamanDuplikasi');
	Route::get('/duplication/sort','Duplication\DuplicationController@sort')->name('duplication.sort');
	Route::get('/duplication/satuan-masalah','Duplication\DuplicationController@cariSatuanBermasalah')->name('duplication.cariSatuanBermasalah');
	// set Kepala Atasan
	// set Nivelering
	Route::get('/duplication/nivelering-norm','Duplication\NiveleringController@niveleringNormalisasi')->name('duplication.niveleringNormalisasi');
	Route::get('/duplication/hapusSatuanKerja','Duplication\DuplicationController@hapusSatuanKerja')->name('duplication.hapusSatuanKerja');
	Route::get('/duplication/hapusSeluruhJabatan','Duplication\DuplicationController@hapusSeluruhJabatan')->name('duplication.hapusSeluruhJabatan');
	Route::get('/masalah/polsubsektor','SatuanController@masalahPolsubsektor')->name('duplication.masalahPolsubsektor');
	Route::get('/masalah/tambah-keterangan-satuan','SatuanController@tambahKeteranganSatuan')->name('duplication.tambahKeteranganSatuan');
	Route::get('/masalah/satuan-double','SatuanController@masalahSatuanDouble')->name('duplication.masalahSatuanDouble');
Route::get('/nivelering-norm','Duplication\DuplicationController@niveleringNormalisasi')->name('duplication.niveleringNormalisasi');
Route::get('/create-eselon','Duplication\DuplicationController@createEselon')->name('duplication.createEselon');
Route::get('/login', 'UserController@getLogin')->name('login');
Route::post('/login', 'UserController@postLogin')->name('user.login.post');
Route::get('/logout', 'UserController@logout')->name('user.logout');



Route::group(['prefix'=>'laporan','namespace'=> 'Laporan','as'=>'laporan.'],function(){
	Route::get('/', 'DashboardController@redirectToLogin');
	Route::get('/login', 'LoginController@getLogin')->name('login.get');
	Route::post('/login', 'LoginController@postLogin')->name('login.post');
	Route::group(['middleware' => 'auth:verifikator'],function(){
		Route::get('/', 'DashboardController@dashboard')->name('dashboard');
	});
});

app/Http/Controllers/Laporan/DashboardController.php
<?php

namespace App\Http\Controllers\Laporan;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
	public function redirectToLogin()
	{
		return redirect()->route('laporan.login');
	}
	public function dashboard()
	{
		return view('laporan.dashboard');
	}
}

app/Http/Controllers/Laporan/LoginController.php
<?php

namespace App\Http\Controllers\Laporan;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;

class LoginController extends Controller
{
	public function getLogin()
	{
		return view('laporan.views.login');
	}
	public function postLogin(Request $request)
	{
	    $error_message = [
		    'nrp.required'    => 'Kolom nrp tidak boleh dikosongkan.',
		    'password.required'    => 'Kolom kata kunci tidak boleh dikosongkan.'
		];

		$validation = Validator::make($request->all(),[
			'nrp' => 'required',
			'password' => 'required'
	    ],$error_message);

	    if($validation->fails()){
	    	
	    }
	    if(auth('verifikator')->attempt(['nrp'=>strtolower($request->nrp),'password' => $request->password,'aktif' => true])){
			return redirect()->route(['laporan.dashboard']);
	    } else{
			return response()->json([
				'errors' => $validation->errors(),
				'status_code' => 400
			], 400);
	    }
	}
}

resources/views/laporan/views/dashboard.blade.php
@extends('laporan.layouts.app')

@section('content')
	<div class="container-fluid">
	    <div class="block-header">
	        <h2>DASHBOARD</h2>
	    </div>

	    @if(Session::has('success'))
		    <div class="alert alert-success">{{Session::get('success')}}</div>
	    @endif

	    @if(Session::has('error'))
		    <div class="alert alert-error">{{Session::get('error')}}</div>
	    @endif

	    <!-- Widgets -->
	    <div class="row clearfix">
	        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
	            <div class="info-box bg-light-blue hover-expand-effect">
	                <div class="icon">
	                    <i class="material-icons">people</i>
	                </div>
	                <div class="content">
	                    <div class="text">PERSONEL</div>
	                    <div class="number count-to" data-from="0" data-to="0" data-speed="15" data-fresh-interval="20"></div>
	                </div>
	            </div>
	        </div>
	    </div>
	    <!-- #END# Widgets -->
	</div>
@endsection

@section('script')
	<script>
	$(function () {
	    //Widgets count
	    $('.count-to').countTo();
	});
	</script>
@endsection

resources/views/laporan/views/login.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>NEWSIPP LAPORAN VERIFIKATOR</title>
    <!-- Favicon-->
    <link rel="icon" href="/favicon.ico" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core Css -->
    <link href="{{ asset('/plugins/bootstrap/css/bootstrap.css') }}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{{ asset('/plugins/node-waves/waves.css') }}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{{ asset('/plugins/animate-css/animate.css') }}" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="{{ asset('/css/style.css') }}" rel="stylesheet">
</head>

<body class="login-page">
    <div class="login-box">
        <div class="logo">
            <a href="javascript:void(0);">NEW<b>SIPP</b></a>
            <small>LAPORAN VERIFIKATOR</small>
        </div>
        <div class="card">
            <div class="body">
                <form id="sign_in" method="POST" action="{{route('laporan.login.post')}}">
                    <div class="msg">Sign in to start your session</div>
                    {!! csrf_field() !!}
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">person</i>
                        </span>
                        <div class="form-line">
                            <input type="text" class="form-control" name="nrp" placeholder="Username" required autofocus>
                        </div>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">lock</i>
                        </span>
                        <div class="form-line">
                            <input type="password" class="form-control" name="password" placeholder="Password" required>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-4">
                            <button class="btn btn-block bg-pink waves-effect" type="submit">SIGN IN</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Jquery Core Js -->
    <script src="{{ asset('/plugins/jquery/jquery.min.js') }}"></script>

    <!-- Bootstrap Core Js -->
    <script src="{{ asset('/plugins/bootstrap/js/bootstrap.js') }}"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="{{ asset('/plugins/node-waves/waves.js') }}"></script>

    <!-- Validation Plugin Js -->
    <script src="{{ asset('/plugins/jquery-validation/jquery.validate.js') }}"></script>

    <!-- Custom Js -->
    <script src="{{ asset('/js/admin.js') }}"></script>
    <script src="{{ asset('/js/pages/examples/sign-in.js') }}"></script>
</body>

</html>