routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/migrasi/migrasi1', 'Migration\Migrasi1Controller@index')->name('migration.migrasi1');


// Route::get('/migrasi/testingmigrasi', 'Migration\Migrasi1Controller@testing')->name('migration.testing');
Route::group(['middleware' => 'auth'], function() {
	Route::get('/', 'SatuanController@redirectToIndex')->name('redirectTo.index');
	Route::get('/dashboard','DashboardController@index')->name('dashboard.index');
	Route::get('/duplikasi-satuan', 'SatuanController@getDuplikasi')->name('satuan.duplication.get');
	Route::post('/duplikasi-satuan', 'SatuanController@postDuplikasi')->name('satuan.duplication.post');
	Route::get('/personel', 'PersonelController@index')->name('personel.index');
	Route::get('/migration', 'Migration\MigrationController@index')->name('migration.index');
	Route::post('/migration/reset-satuan-jabatan', 'MigrationController@resetSatuanJabatan')->name('migration.reset.satuan-jabatan');
	Route::post('/migration/reset-personel', 'MigrationController@resetPersonel')->name('migration.reset.personel');
	Route::get('/migration/insert-jabatan', 'MigrationController@insertJabatan')->name('migration.insert.jabatan');
	Route::post('/migration/seed', 'MigrationController@seed')->name('migration.seed');
	Route::get('/personel/{personel}/edit', 'PersonelController@edit')->name('personel.edit');
	Route::post('/personel/{personel}/update', 'PersonelController@update')->name('personel.update');
	Route::get('/personel/filter', 'PersonelController@filter')->name('personel.filter');
	Route::get('/personel/duplicate', 'PersonelController@duplicate')->name('personel.duplicate');
	Route::patch('/personel/verification/{id}', 'PersonelController@verification')->name('personel.verification');
	Route::get('/personel/create', 'PersonelController@create')->name('personel.create');


	Route::post('/satuan/filter', 'SatuanController@filter')->name('satuan.filter');
	Route::resource('/satuan','SatuanController');
	Route::get('/satuan/{satuan}/create-satuan', 'SatuanController@createSatuan')->name('satuan.create-satuan');
	// Route::get('/get-data-wiget/{satuan}', 'SatuanController@APIdataWidget')->name('satuan.api-data-widget');
	Route::post('/satuan/{satuan}/store-satuan', 'SatuanController@storeSatuan')->name('satuan.store-satuan');
	Route::get('/satuan/{satuan}/create-jabatan', 'SatuanController@createJabatan')->name('satuan.create-jabatan');
	Route::post('/satuan/{satuan}/store-jabatan', 'SatuanController@storeJabatan')->name('satuan.store-jabatan');
	Route::get('/satuan/verification/{satuan}', 'SatuanController@verification')->name('satuan.verification');
	Route::get('/satuan/{satuan}/edit-jabatan/{satuanJabatan}', 'SatuanJabatanController@edit')->name('satuan-jabatan.edit');
	Route::patch('/satuan/{satuan}/update-jabatan/{satuanJabatan}', 'SatuanJabatanController@update')->name('satuan-jabatan.update');
	Route::delete('/satuan/{satuan}/delete-jabatan/{satuanJabatan}', 'SatuanJabatanController@destroy')->name('satuan-jabatan.destroy');
	Route::post('/satuan/{satuan}/verification/{satuanJabatan}', 'SatuanJabatanController@verification')->name('satuan-jabatan.verification');
	Route::post('/satuan/{satuan}/data-error/{satuanJabatan}', 'SatuanJabatanController@dataError')->name('satuan-jabatan.data-error');


	Route::get('/jabatan-filter', 'JabatanController@filter')->name('jabatan.filter');


	Route::resource('/jenis-satuan','JenisSatuanController');
	Route::resource('/jabatan','JabatanController');
	Route::resource('/pangkat','PangkatController');
	Route::resource('/nivelering','NiveleringController');


});

Route::get('/testing-request','API\FileController@getFileTesting');
Route::get('/report-harian','ReportController@reportHarian')->name('report.harian');
Route::get('/', 'UserController@getLogin');
// Duplication
	Route::get('/duplication/duplikasi','Duplication\DuplicationController@halamanDuplikasi')->name('duplication.halamanDuplikasi');
	Route::get('/duplication/sort','Duplication\DuplicationController@sort')->name('duplication.sort');
	Route::get('/duplication/satuan-masalah','Duplication\DuplicationController@cariSatuanBermasalah')->name('duplication.cariSatuanBermasalah');
	// set Kepala Atasan
	// set Nivelering
	Route::get('/duplication/nivelering-norm','Duplication\NiveleringController@niveleringNormalisasi')->name('duplication.niveleringNormalisasi');
	Route::get('/duplication/hapusSatuanKerja','Duplication\DuplicationController@hapusSatuanKerja')->name('duplication.hapusSatuanKerja');
	Route::get('/duplication/hapusSeluruhJabatan','Duplication\DuplicationController@hapusSeluruhJabatan')->name('duplication.hapusSeluruhJabatan');
	Route::get('/masalah/polsubsektor','SatuanController@masalahPolsubsektor')->name('duplication.masalahPolsubsektor');
	Route::get('/masalah/tambah-keterangan-satuan','SatuanController@tambahKeteranganSatuan')->name('duplication.tambahKeteranganSatuan');
	Route::get('/masalah/satuan-double','SatuanController@masalahSatuanDouble')->name('duplication.masalahSatuanDouble');
Route::get('/nivelering-norm','Duplication\DuplicationController@niveleringNormalisasi')->name('duplication.niveleringNormalisasi');
Route::get('/create-eselon','Duplication\DuplicationController@createEselon')->name('duplication.createEselon');
Route::get('/login', 'UserController@getLogin')->name('login');
Route::post('/login', 'UserController@postLogin')->name('user.login.post');
Route::get('/logout', 'UserController@logout')->name('user.logout');



Route::group(['prefix'=>'laporan','namespace'=> 'Laporan','as'=>'laporan.'],function(){
	Route::get('/', 'DashboardController@redirectToLogin');
	Route::get('/login', 'LoginController@getLogin')->name('login.get');
	Route::post('/login', 'LoginController@postLogin')->name('login.post');
	Route::group(['middleware' => 'auth:verifikator'],function(){
		Route::get('/', 'DashboardController@dashboard')->name('dashboard');
	});
});

app/Http/Controllers/API/SatuanController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Satuan;
use App\SatuanJabatan;
use Illuminate\Http\Request;
use Cache;

class SatuanController extends Controller
{
	public function listChild(Request $request)
	{
		$satuanID = $request->satuan_id ?? 1;
		$dataSatuan = Satuan::active()->where('parent_id',$satuanID)->select(['satuan_id','nama_satuan'])->orderBy('nama_satuan')->get();
		return response()->json([
			'data' => $dataSatuan->toArray()
		], 200);
	}
	public function listJabatan($satuanID)
	{
		$dataSatuanJabatan = SatuanJabatan::with('jabatan')->where('satuan_id',$satuanID)->orderBy('jabatan.nama_jabatan')->get();

		return response()->json([
			'data' => $dataSatuanJabatan->toArray()
		], 200);
	}

	public function daftarSatuanPertama()
	{
		$dataSatuan = Satuan::where('parent_id',1)->select(['satuan_id','nama_satuan'])->orderBy('nama_satuan')->get();
		return response()->json([
			'data' => $dataSatuan->toArray()
		], 200);
	}
	public function daftarSatuan(Satuan $satuan)
	{
		$satuanID=$satuan->satuan_id;
		$dataSatuan=Satuan::select(['satuan_id','nama_satuan'])->where('parent_id',$satuan->satuan_id)->orderBy('nama_satuan')->get();
		return response()->json([
			'data' => $dataSatuan->toArray()
		],200);
	}
	public function daftarSatuanAktif(Satuan $satuan)
	{
		$satuanID=$satuan->satuan_id;
		 $dataSatuan=Satuan::select(['satuan_id','nama_satuan'])->where('tipe','STRUKTUR')->whereNull('deleted_by')->where('parent_id',$satuan->satuan_id)->orderBy('nama_satuan')->get();
		return response()->json([
			'data' => $dataSatuan->toArray()
		],200);
	}
	public function daftarJabatan(Satuan $satuan)
	{
		return response()->json([
			'data' => $satuan->jabatan
		],200);
	}
}

app/Http/Controllers/Migration/Satuan/JenisPolsekController.php
<?php

namespace App\Http\Controllers\Migration\Satuan;

use App\Http\Controllers\Controller;
use App\JenisSatuan;
use App\MigrationStatus;
use App\Satuan;
use Carbon\Carbon;
use Illuminate\Http\Request;

class JenisPolsekController extends Controller
{
    public function index()
    {
        echo 'insertPOLSEKURBAN';
        $countSkipPolsekUrban = $this->insertPOLSEKURBAN();
        echo 'insertPOLSEKRURAL';
        $countSkipPolsekRural = $this->insertPOLSEKRURAL();
        echo 'insertPOLSEKPRARURAL';
        $countSkipPolsekPrarural = $this->insertPOLSEKPRARURAL();
        echo 'insertPOLSEKMETRO';
        $countSkipPolsekMetro = $this->insertPOLSEKMETRO();
        echo 'insertPOLSUBSEKTOR';
        $countSkipPolsekSubSektor = $this->insertPOLSUBSEKTOR();

        $temp = $countSkipPolsekUrban.','.$countSkipPolsekRural.','.$countSkipPolsekPrarural.','.$countSkipPolsekMetro.','.$countSkipPolsekSubSektor;
        $migrationStatus = MigrationStatus::find(2);
        $migrationStatus->migration_date=Carbon::now();
        $migrationStatus->save();
        
        return redirect('migration')->with('success',"Berhasil melakukan migrasi satuan polsek ".$temp);
    }
    public function insertPOLSUBSEKTOR()
    {
        $i=0;
        $jenisSatuan = JenisSatuan::where('nama_jenis_satuan','POLSEK SUBSEKTOR')->first();
        $daftarPOLSEKSUBSEKTOR = $jenisSatuan->satuan()->get();
        foreach($daftarPOLSEKSUBSEKTOR as $POLSEKSUBSEKTOR){
            $jenisSatker = JenisSatuan::where('kategori','SATUAN KERJA')->pluck('jenis_satuan_id')->toArray();
            if($POLSEKSUBSEKTOR->childs()->whereIn('jenis_satuan_id',$jenisSatker)->count()>0){
                $i++;
                continue;
            }

            $satuan = Satuan::createSatuan('URMIN','UR',$POLSEKSUBSEKTOR);
            
            $satuan = Satuan::createSatuan('UNIT PATROLI','UNIT',$POLSEKSUBSEKTOR);
            
            $satuan = Satuan::createSatuan('UNIT YANMAS','UNIT',$POLSEKSUBSEKTOR);
        }
        return $i;
    }

    public function insertPOLSEKPRARURAL()
    {
        $i=0;
        $jenisSatuan = JenisSatuan::where('nama_jenis_satuan','POLSEK PRARURAL')->first();
        $daftarPOLSEKPRARURAL = $jenisSatuan->satuan()->get();
        foreach($daftarPOLSEKPRARURAL as $POLSEKPRARURAL){
            $jenisSatker = JenisSatuan::where('kategori','SATUAN KERJA')->pluck('jenis_satuan_id')->toArray();
            if($POLSEKPRARURAL->childs()->whereIn('jenis_satuan_id',$jenisSatker)->count()>0){
                $i++;
                continue;
            }
            $satuan = Satuan::createSatuan('UNIT PROVOS','UNIT',$POLSEKPRARURAL);
            $bag = Satuan::createSatuan('SIUM','SI',$POLSEKPRARURAL);
                Satuan::createSatuan('URRENMIN','UR',$bag);
                Satuan::createSatuan('URTAUD','UR',$bag);
                Satuan::createSatuan('URTAHTI','UR',$bag);
            $satuan = Satuan::createSatuan('SENTRA PELAYANAN KEPOLISIAN TERPADU','SENTRA PELAYANAN',$POLSEKPRARURAL);
            $satuan = Satuan::createSatuan('UNIT INTELKAM','UNIT',$POLSEKPRARURAL);
            $satuan = Satuan::createSatuan('UNIT RESKRIM','UNIT',$POLSEKPRARURAL);
            $satuan = Satuan::createSatuan('UNIT BINMAS','UNIT',$POLSEKPRARURAL);
            $satuan = Satuan::createSatuan('UNIT SABHARA','UNIT',$POLSEKPRARURAL);
            $satuan = Satuan::createSatuan('UNIT LANTAS','UNIT',$POLSEKPRARURAL);
            $satuan = Satuan::createSatuan('UNIT POLAIR','UNIT',$POLSEKPRARURAL);
        }
        return $i;
    }
    public function insertPOLSEKRURAL()
    {
        $i=0;
        $jenisSatuan = JenisSatuan::where('nama_jenis_satuan','POLSEK RURAL')->first();
        $daftarPOLSEKRURAL = $jenisSatuan->satuan()->get();
        foreach($daftarPOLSEKRURAL as $POLSEKRURAL){
            $jenisSatker = JenisSatuan::where('kategori','SATUAN KERJA')->pluck('jenis_satuan_id')->toArray();
            if($POLSEKRURAL->childs()->whereIn('jenis_satuan_id',$jenisSatker)->count()>0){
                $i++;
                continue;
            }
            $satuan = Satuan::createSatuan('UNIT PROVOS','UNIT',$POLSEKRURAL);
            $bag = Satuan::createSatuan('SIUM','SI',$POLSEKRURAL);
                Satuan::createSatuan('URRENMIN','UR',$bag);
                Satuan::createSatuan('URTAUD','UR',$bag);
                Satuan::createSatuan('URTAHTI','UR',$bag);
            $satuan = Satuan::createSatuan('SIHUMAS','SI',$POLSEKRURAL);
            $satuan = Satuan::createSatuan('SENTRA PELAYANAN KEPOLISIAN TERPADU','SENTRA PELAYANAN',$POLSEKRURAL);
            $satuan = Satuan::createSatuan('UNIT INTELKAM','UNIT',$POLSEKRURAL);
            $satuan = Satuan::createSatuan('UNIT RESKRIM','UNIT',$POLSEKRURAL);
            $satuan = Satuan::createSatuan('UNIT BINMAS','UNIT',$POLSEKRURAL);
            $satuan = Satuan::createSatuan('UNIT SABHARA','UNIT',$POLSEKRURAL);
            $satuan = Satuan::createSatuan('UNIT LANTAS','UNIT',$POLSEKRURAL);
            $satuan = Satuan::createSatuan('UNIT POLAIR','UNIT',$POLSEKRURAL);
        }
        return $i;
    }
    public function insertPOLSEKMETRO()
    {
        $i=0;
        $jenisSatuan = JenisSatuan::where('nama_jenis_satuan','POLSEK METRO')->first();
        $daftarPOLSEKMETRO = $jenisSatuan->satuan()->get();
        foreach($daftarPOLSEKMETRO as $POLSEKMETRO){
            $jenisSatker = JenisSatuan::where('kategori','SATUAN KERJA')->pluck('jenis_satuan_id')->toArray();
            if($POLSEKMETRO->childs()->whereIn('jenis_satuan_id',$jenisSatker)->count()>0){
                $i++;
                continue;
            }
            $satuan = Satuan::createSatuan('UNIT PROVOS','UNIT',$POLSEKMETRO);
            $bag = Satuan::createSatuan('SIUM','SI',$POLSEKMETRO);
                Satuan::createSatuan('URRENMIN','UR',$bag);
                Satuan::createSatuan('URTAUD','UR',$bag);
                Satuan::createSatuan('URTAHTI','UR',$bag);
            $satuan = Satuan::createSatuan('SIKUM','SI',$POLSEKMETRO);
            $satuan = Satuan::createSatuan('SIHUMAS','SI',$POLSEKMETRO);
            $satuan = Satuan::createSatuan('SENTRA PELAYANAN KEPOLISIAN TERPADU','SENTRA PELAYANAN',$POLSEKMETRO);
            $satuan = Satuan::createSatuan('UNIT INTELKAM','UNIT',$POLSEKMETRO);
            $satuan = Satuan::createSatuan('UNIT RESKRIM','UNIT',$POLSEKMETRO);
            $satuan = Satuan::createSatuan('UNIT BINMAS','UNIT',$POLSEKMETRO);
            $satuan = Satuan::createSatuan('UNIT SABHARA','UNIT',$POLSEKMETRO);
            $satuan = Satuan::createSatuan('UNIT LANTAS','UNIT',$POLSEKMETRO);
            $satuan = Satuan::createSatuan('UNIT POLAIR','UNIT',$POLSEKMETRO);
        }
        return $i;
    }
    public function insertPOLSEKURBAN()
    {
        $i=0;
        $jenisSatuan = JenisSatuan::where('nama_jenis_satuan','POLSEK URBAN')->first();
        $daftarPOLSEKURBAN = $jenisSatuan->satuan()->get();
        foreach($daftarPOLSEKURBAN as $POLSEKURBAN){
            $jenisSatker = JenisSatuan::where('kategori','SATUAN KERJA')->pluck('jenis_satuan_id')->toArray();
            if($POLSEKURBAN->childs()->whereIn('jenis_satuan_id',$jenisSatker)->count()>0){
                $i++;
                continue;
            }
            $satuan = Satuan::createSatuan('UNIT PROVOS','UNIT',$POLSEKURBAN);
            $bag = Satuan::createSatuan('SIUM','SI',$POLSEKURBAN);
                Satuan::createSatuan('URRENMIN','UR',$bag);
                Satuan::createSatuan('URTAUD','UR',$bag);
                Satuan::createSatuan('URTAHTI','UR',$bag);
            $satuan = Satuan::createSatuan('SIKUM','SI',$POLSEKURBAN);
            $satuan = Satuan::createSatuan('SIHUMAS','SI',$POLSEKURBAN);
            $satuan = Satuan::createSatuan('SENTRA PELAYANAN KEPOLISIAN TERPADU','SENTRA PELAYANAN',$POLSEKURBAN);
            $satuan = Satuan::createSatuan('UNIT INTELKAM','UNIT',$POLSEKURBAN);
            $satuan = Satuan::createSatuan('UNIT RESKRIM','UNIT',$POLSEKURBAN);
            $satuan = Satuan::createSatuan('UNIT BINMAS','UNIT',$POLSEKURBAN);
            $satuan = Satuan::createSatuan('UNIT SABHARA','UNIT',$POLSEKURBAN);
            $satuan = Satuan::createSatuan('UNIT LANTAS','UNIT',$POLSEKURBAN);
            $satuan = Satuan::createSatuan('UNIT POLAIR','UNIT',$POLSEKURBAN);
        }
        return $i;
    }
}

resources/views/satuan/index.blade.php
@extends('layouts.default')

@section('content')
	<div class="container-fluid">
	    <div class="block-header">
	        <h2>DASHBOARD</h2>
	    </div>

	    @if(Session::has('success'))
		    <div class="alert alert-success">{{Session::get('success')}}</div>
	    @endif

	    @if(Session::has('error'))
		    <div class="alert alert-error">{{Session::get('error')}}</div>
	    @endif

	    <!-- Widgets -->
	    <div class="row clearfix">
	        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
	            <div class="info-box bg-light-blue hover-expand-effect">
	                <div class="icon">
	                    <i class="material-icons">people</i>
	                </div>
	                <div class="content">
	                    <div class="text">SATUAN TERVERIFIKASI</div>
			            <div class="preloader" style="width:20px; height:20px;">
			                <div class="spinner-layer pl-white">
			                    <div class="circle-clipper left">
			                        <div class="circle"></div>
			                    </div>
			                </div>
			            </div>
			            <div class="api-widget hidden">
		                    <div id="totalVerifiedSatuan">0</div> dari 
		                    <div id="totalSatuan">0</div>
			            </div>
	                </div>
	            </div>
	        </div>
	        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
	            <div class="info-box bg-light-green hover-expand-effect">
	                <div class="icon">
	                    <i class="material-icons">check</i>
	                </div>
	                <div class="content">
	                    <div class="text">JENIS SATUAN</div>
	                    <div class="number count-to" data-from="0" data-to="{{$jumlahJenisSatuan}}" data-speed="15" data-fresh-interval="20"></div>
	                </div>
	            </div>
	        </div>
	        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
	            <div class="info-box bg-red hover-expand-effect">
	                <div class="icon">
	                    <i class="material-icons">forum</i>
	                </div>
	                <div class="content">
	                    <div class="text">JENIS JABATAN</div>
	                    <div class="number count-to" data-from="0" data-to="{{$jumlahJabatan}}" data-speed="1000" data-fresh-interval="20"></div>
	                </div>
	            </div>
	        </div>
	        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
	            <div class="info-box bg-orange hover-expand-effect">
	                <div class="icon">
	                    <i class="material-icons">forum</i>
	                </div>
	                <div class="content">
	                    <div class="text">JABATAN TERVERIFIKASI</div>
			            <div class="preloader" style="width:20px; height:20px;">
			                <div class="spinner-layer pl-white">
			                    <div class="circle-clipper left">
			                        <div class="circle"></div>
			                    </div>
			                </div>
			            </div>
			            <div class="api-widget hidden">
		                    <div id="totalVerifiedJabatan">0</div> dari 
		                    <div id="totalJabatan">0</div>
		                </div>
	                </div>
	            </div>
	        </div>
	    </div>
	    <!-- #END# Widgets -->

	    <div class="row m-b-10">
	    	<div class="col-md-4"><a href="{{ route('satuan.create')}}" class="btn btn-success btn-block">Buat Satuan</a></div>
	    	<div class="col-md-4"><a href="{{ route('jenis-satuan.create')}}" class="btn btn-success btn-block">Buat Jenis Satuan</a></div>
	    </div>


	    <!-- Filter -->
	    <div class="row clearfix" id="filter">
	        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
	            <div class="card">
	                <div class="header">
	                    <h2>FILTER</h2>
	                </div>
	                <div class="body">
	                    <form id="form_validation" class="form-horizontal" method="POST" action="{{route('satuan.filter')}}">
	                    	{{ csrf_field() }}
	                        <div class="row clearfix">
	                            <div class="col-md-12">
	                                <div class="row clearfix">
	                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-5 form-control-label">
	                                        <label for="nama_satuan">Nama Satuan</label>
	                                    </div>
	                                    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-7">
	                                        <div class="form-group" style="margin:0px;">
	                                            <div class="form-line" style="padding-left:12px;">
	                                                <input id="nama_satuan" name="nama_satuan" class="form-control" placeholder="Masukkan Nama Satuan" type="text">
	                                            </div>
	                                        </div>
	                                    </div>
	                                </div>
	                                <div class="row clearfix">
	                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-5 form-control-label">
	                                        <label for="jenis_satuan_id">Jenis Satuan</label>
	                                    </div>
	                                    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-7">
		                                    <select class="form-control show-tick" name="jenis_satuan_id" id="jenis_satuan_id">
		                                        <option value="all">SEMUA JENIS SATUAN</option>
		                                        @foreach($dataJenisSatuan as $jenisSatuan)
		                                        <option value="{{$jenisSatuan->jenis_satuan_id}}">{{$jenisSatuan->nama_jenis_satuan}}</option>
		                                        @endforeach
		                                    </select>
	                                    </div>
	                                </div>
	                                <div class="row clearfix">
	                                    <div class="col-md-8 col-md-offset-4">
	                                        <button type="submit" class="btn bg-green btn-lg btn-block waves-effect"><label><i class="material-icons">search</i> CARI</label></button>
	                                    </div>
	                                </div>
	                            </div>
	                        </div>
	                    </form>
	                </div>
	            </div>
	        </div>
	    </div>
	    <!-- End Filter -->
	    
	    <!-- Hover Rows -->
	    <div class="row clearfix">
	        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
	            <div class="card">
	            	<div class="header">
	            	<h2>Daftar Satuan</h2>
	            	</div>
	                <div class="body table-responsive">
	                    <table class="table table-hover" id="table-personel">
	                        <thead>
	                            <tr>
	                                <th>ID</th>
	                                <th width="350px">Nama Satuan</th>
	                                <th width="150px">Jumlah Satuan</th>
	                                <th width="200px">Tipe Satuan</th>
	                                <th width="100px">Status</th>
	                                <th width="100px">PILIHAN</th>
	                            </tr>
	                        </thead>
	                        <tbody>
	                            @foreach($dataSatuan as $satuan)
	                            <tr style="font-size:12px;">
	                            	<td>{{ $satuan->satuan_id }}</td>
	                            	<td>{{ $satuan->nama_satuan }}</td>
	                            	<td>{{ $satuan->childs()->count() }}</td>
	                            	<td>{{ $satuan->tipe }}</td>
	                            	<td>{!! $satuan->printStatus() !!}<br>
	                            		@if($satuan->verified_by==null)
	                            		<a href="{{route('satuan.verification',$satuan->satuan_id)}}" class="btn btn-success" style="margin-top: 10px;">Verifikasi</a>
	                            		@else
	                            		<a href="{{route('satuan.verification',$satuan->satuan_id)}}" class="btn btn-success" style="margin-top: 10px;">Tidak terverifikasi</a>
	                            		@endif
		                            </td>
	                            	<td>
		                            	<a href="{{route('satuan.show',$satuan->satuan_id)}}" class="btn btn-xs bg-blue"><i class="material-icons">pageview</i></a>
	                            	</td>
	                            </tr>
	                            @endforeach
	                        </tbody>
	                    </table>
	                    {{ $dataSatuan->render() }}
	                </div>
	            </div>
	        </div>
	    </div>
	    <!-- #END# Hover Rows -->

	    <!-- Hover Rows -->
	    <div class="row clearfix">
	        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
	            <div class="card">
	            	<div class="header">
	            	<h2>Jenis Satuan</h2>
	            	</div>
	                <div class="body table-responsive">
	                    <table class="table table-hover" id="table-personel">
	                        <thead>
	                            <tr>
	                                <th width="400px">Jenis Satuan</th>
	                                <th width="200px">Kategori Satuan</th>
	                                <th>Jumlah Satuan</th>
	                                <th>PILIHAN</th>
	                            </tr>
	                        </thead>
	                        <tbody>
	                            @foreach($dataJenisSatuan as $jenisSatuan)
	                            <tr style="font-size:12px;">
	                            	<td>{{ $jenisSatuan->jenis_satuan_id }}</td>
	                            	<td>{{ $jenisSatuan->nama_jenis_satuan }}</td>
	                            	<td>{{ $jenisSatuan->satuan()->count() }}</td>
	                            	<td>{{ $jenisSatuan->kategori }}</td>
	                            	<td>
		                            	<a href="{{route('jenis-satuan.edit',$jenisSatuan->jenis_satuan_id)}}" class="btn btn-xs bg-blue"><i class="material-icons">pageview</i></a>
<!-- 	                            		<a onclick="confirmDelete('{{route('jenis-satuan.destroy',$jenisSatuan->jenis_satuan_id)}}')"><button class="btn btn-xs bg-red waves-effect" type="button" title="delete"><i class="material-icons">delete_forever</i></button></a> -->
	                            	</td>
	                            </tr>
	                            @endforeach
	                        </tbody>
	                    </table>
	                    {{ $dataSatuan->render() }}
	                </div>
	            </div>
	        </div>
	    </div>
	    <!-- #END# Hover Rows -->
	</div>
@endsection

@section('script')
	<script>
	$(function () {
	    //Widgets count
	    $('.count-to').countTo();
	});
	</script>
@endsection