routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/migrasi/migrasi1', 'Migration\Migrasi1Controller@index')->name('migration.migrasi1');


// Route::get('/migrasi/testingmigrasi', 'Migration\Migrasi1Controller@testing')->name('migration.testing');
Route::group(['middleware' => 'auth'], function() {
	Route::get('/', 'SatuanController@redirectToIndex')->name('redirectTo.index');
	Route::get('/dashboard','DashboardController@index')->name('dashboard.index');
	Route::get('/duplikasi-satuan', 'SatuanController@getDuplikasi')->name('satuan.duplication.get');
	Route::post('/duplikasi-satuan', 'SatuanController@postDuplikasi')->name('satuan.duplication.post');
	Route::get('/personel', 'PersonelController@index')->name('personel.index');
	Route::get('/migration', 'Migration\MigrationController@index')->name('migration.index');
	Route::post('/migration/reset-satuan-jabatan', 'MigrationController@resetSatuanJabatan')->name('migration.reset.satuan-jabatan');
	Route::post('/migration/reset-personel', 'MigrationController@resetPersonel')->name('migration.reset.personel');
	Route::get('/migration/insert-jabatan', 'MigrationController@insertJabatan')->name('migration.insert.jabatan');
	Route::post('/migration/seed', 'MigrationController@seed')->name('migration.seed');
	Route::get('/personel/{personel}/edit', 'PersonelController@edit')->name('personel.edit');
	Route::post('/personel/{personel}/update', 'PersonelController@update')->name('personel.update');
	Route::get('/personel/filter', 'PersonelController@filter')->name('personel.filter');
	Route::get('/personel/duplicate', 'PersonelController@duplicate')->name('personel.duplicate');
	Route::patch('/personel/verification/{id}', 'PersonelController@verification')->name('personel.verification');
	Route::get('/personel/create', 'PersonelController@create')->name('personel.create');


	Route::post('/satuan/filter', 'SatuanController@filter')->name('satuan.filter');
	Route::resource('/satuan','SatuanController');
	Route::get('/satuan/{satuan}/create-satuan', 'SatuanController@createSatuan')->name('satuan.create-satuan');
	// Route::get('/get-data-wiget/{satuan}', 'SatuanController@APIdataWidget')->name('satuan.api-data-widget');
	Route::post('/satuan/{satuan}/store-satuan', 'SatuanController@storeSatuan')->name('satuan.store-satuan');
	Route::get('/satuan/{satuan}/create-jabatan', 'SatuanController@createJabatan')->name('satuan.create-jabatan');
	Route::post('/satuan/{satuan}/store-jabatan', 'SatuanController@storeJabatan')->name('satuan.store-jabatan');
	Route::get('/satuan/verification/{satuan}', 'SatuanController@verification')->name('satuan.verification');
	Route::get('/satuan/{satuan}/edit-jabatan/{satuanJabatan}', 'SatuanJabatanController@edit')->name('satuan-jabatan.edit');
	Route::patch('/satuan/{satuan}/update-jabatan/{satuanJabatan}', 'SatuanJabatanController@update')->name('satuan-jabatan.update');
	Route::delete('/satuan/{satuan}/delete-jabatan/{satuanJabatan}', 'SatuanJabatanController@destroy')->name('satuan-jabatan.destroy');
	Route::post('/satuan/{satuan}/verification/{satuanJabatan}', 'SatuanJabatanController@verification')->name('satuan-jabatan.verification');
	Route::post('/satuan/{satuan}/data-error/{satuanJabatan}', 'SatuanJabatanController@dataError')->name('satuan-jabatan.data-error');


	Route::get('/jabatan-filter', 'JabatanController@filter')->name('jabatan.filter');


	Route::resource('/jenis-satuan','JenisSatuanController');
	Route::resource('/jabatan','JabatanController');
	Route::resource('/pangkat','PangkatController');
	Route::resource('/nivelering','NiveleringController');


});

Route::get('/testing-request','API\FileController@getFileTesting');
Route::get('/report-harian','ReportController@reportHarian')->name('report.harian');
Route::get('/', 'UserController@getLogin');
// Duplication
	Route::get('/duplication/duplikasi','Duplication\DuplicationController@halamanDuplikasi')->name('duplication.halamanDuplikasi');
	Route::get('/duplication/sort','Duplication\DuplicationController@sort')->name('duplication.sort');
	Route::get('/duplication/satuan-masalah','Duplication\DuplicationController@cariSatuanBermasalah')->name('duplication.cariSatuanBermasalah');
	// set Kepala Atasan
	// set Nivelering
	Route::get('/duplication/nivelering-norm','Duplication\NiveleringController@niveleringNormalisasi')->name('duplication.niveleringNormalisasi');
	Route::get('/duplication/hapusSatuanKerja','Duplication\DuplicationController@hapusSatuanKerja')->name('duplication.hapusSatuanKerja');
	Route::get('/duplication/hapusSeluruhJabatan','Duplication\DuplicationController@hapusSeluruhJabatan')->name('duplication.hapusSeluruhJabatan');
	Route::get('/masalah/polsubsektor','SatuanController@masalahPolsubsektor')->name('duplication.masalahPolsubsektor');
	Route::get('/masalah/tambah-keterangan-satuan','SatuanController@tambahKeteranganSatuan')->name('duplication.tambahKeteranganSatuan');
	Route::get('/masalah/satuan-double','SatuanController@masalahSatuanDouble')->name('duplication.masalahSatuanDouble');
Route::get('/nivelering-norm','Duplication\DuplicationController@niveleringNormalisasi')->name('duplication.niveleringNormalisasi');
Route::get('/create-eselon','Duplication\DuplicationController@createEselon')->name('duplication.createEselon');
Route::get('/login', 'UserController@getLogin')->name('login');
Route::post('/login', 'UserController@postLogin')->name('user.login.post');
Route::get('/logout', 'UserController@logout')->name('user.logout');



Route::group(['prefix'=>'laporan','namespace'=> 'Laporan','as'=>'laporan.'],function(){
	Route::get('/', 'DashboardController@redirectToLogin');
	Route::get('/login', 'LoginController@getLogin')->name('login.get');
	Route::post('/login', 'LoginController@postLogin')->name('login.post');
	Route::group(['middleware' => 'auth:verifikator'],function(){
		Route::get('/', 'DashboardController@dashboard')->name('dashboard');
	});
});

app/Nivelering.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Nivelering extends Model
{
	protected $table = 'nivelering';
	protected $primaryKey = 'nivelering_id';
	protected $fillable = ['nivelering_id','nama_nivelering'];
	public $timestamps = false;
}

app/Http/Controllers/Duplication/NiveleringController.php
<?php

namespace App\Http\Controllers\Duplication;

use App\Http\Controllers\Controller;
use App\SatuanJabatan;
use Illuminate\Http\Request;

class NiveleringController extends Controller
{
	public function niveleringNormalisasi()
	{
		SatuanJabatan::where('nivelering_id',5)->update(['nivelering_id' => 4]);
		SatuanJabatan::where('nivelering_id',6)->update(['nivelering_id' => 5]);
		SatuanJabatan::where('nivelering_id',7)->update(['nivelering_id' => 6]);
		SatuanJabatan::where('nivelering_id',9)->update(['nivelering_id' => 7]);
		SatuanJabatan::where('nivelering_id',10)->update(['nivelering_id' => 8]);
		SatuanJabatan::where('nivelering_id',12)->update(['nivelering_id' => 9]);
		SatuanJabatan::where('nivelering_id',13)->update(['nivelering_id' => 10]);
		SatuanJabatan::where('nivelering_id',14)->update(['nivelering_id' => 11]);
		SatuanJabatan::where('nivelering_id',17)->update(['nivelering_id' => 12]);
	}
}

app/Http/Controllers/NiveleringController.php
<?php

namespace App\Http\Controllers;

use App\Nivelering;
use Illuminate\Http\Request;

class NiveleringController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dataNivelering = Nivelering::paginate(60);
        $niveleringCount = Nivelering::count();
        return view('nivelering.index')
            ->with('niveleringCount',$niveleringCount)
            ->with('dataNivelering',$dataNivelering);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Nivelering $nivelering)
    {
        if($nivelering->delete()){
            return redirect()->route('nivelering.index')->with('success','Hapus nivelering berhasil.');
        } else{
            return redirect()->route('nivelering.index')->with('error','Hapus nivelering gagal.');
        }
    }
}

resources/views/nivelering/index.blade.php
@extends('layouts.default')

@section('content')
	<div class="container-fluid">
	    <div class="block-header">
	        <h2>DASHBOARD</h2>
	    </div>

	    @if(Session::has('success'))
		    <div class="alert alert-success">{{Session::get('success')}}</div>
	    @endif

	    @if(Session::has('error'))
		    <div class="alert alert-error">{{Session::get('error')}}</div>
	    @endif

	    <!-- Widgets -->
	    <div class="row clearfix">
	        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
	            <div class="info-box bg-light-blue hover-expand-effect">
	                <div class="icon">
	                    <i class="material-icons">people</i>
	                </div>
	                <div class="content">
	                    <div class="text">JUMLAH</div>
	                    <div class="number count-to" data-from="0" data-to="{{$niveleringCount}}" data-speed="15" data-fresh-interval="20"></div>
	                </div>
	            </div>
	        </div>
	    </div>
	    <!-- #END# Widgets -->
	    

	    <!-- Hover Rows -->
	    <div class="row clearfix">
	        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
	            <div class="card">
	                <div class="body table-responsive">
	                    <table class="table table-hover" id="table-personel">
	                        <thead>
	                            <tr>
	                                <th>ID</th>
	                                <th width="200px">Nama Nivelering</th>
	                                <th>PILIHAN</th>
	                            </tr>
	                        </thead>
	                        <tbody>
	                            @foreach($dataNivelering as $nivelering)
	                            <tr style="font-size:12px;">
	                            	<td>{{$nivelering->nivelering_id}}</td>
	                            	<td>{{$nivelering->nama_nivelering}}</td>
	                            	<td>
										<a onclick="confirmDelete('{{ route('nivelering.destroy',$nivelering->nivelering_id) }}')"><button class="btn btn-xs bg-red waves-effect" type="button" title="delete"><i class="material-icons">delete_forever</i></button></a>
									</td>
	                            </tr>
	                            @endforeach
	                        </tbody>
	                    </table>
	                    {{ $dataNivelering->render() }}
	                </div>
	            </div>
	        </div>
	    </div>
	    <!-- #END# Hover Rows -->
	</div>
@endsection
@section('script')
	<script>
	$(function () {
	    //Widgets count
	    $('.count-to').countTo();
	});
	</script>
@endsection